#!/usr/bin/env python3
"""Scan generated Anvil region files for E2 worldgen target blocks.

The scanner intentionally avoids third-party dependencies so it can run in the
pack repository. It reads modern Java chunk NBT, decodes section palettes, and
counts block states generated by the OpenLoader datapack.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import math
import struct
import sys
import zlib
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DATAPACK = ROOT / "config/openloader/data/e2_worldgen/data/e2_worldgen/worldgen/configured_feature"
DEFAULT_REPORT = ROOT / "audit/worldgen_save_scan.md"
DEFAULT_CSV = ROOT / "audit/worldgen_save_scan.csv"


class NbtReader:
    def __init__(self, data: bytes):
        self.data = data
        self.pos = 0

    def read(self, size: int) -> bytes:
        out = self.data[self.pos : self.pos + size]
        if len(out) != size:
            raise EOFError("unexpected end of NBT data")
        self.pos += size
        return out

    def u8(self) -> int:
        return self.read(1)[0]

    def i8(self) -> int:
        return struct.unpack(">b", self.read(1))[0]

    def i16(self) -> int:
        return struct.unpack(">h", self.read(2))[0]

    def i32(self) -> int:
        return struct.unpack(">i", self.read(4))[0]

    def i64(self) -> int:
        return struct.unpack(">q", self.read(8))[0]

    def f32(self) -> float:
        return struct.unpack(">f", self.read(4))[0]

    def f64(self) -> float:
        return struct.unpack(">d", self.read(8))[0]

    def string(self) -> str:
        length = struct.unpack(">H", self.read(2))[0]
        return self.read(length).decode("utf-8")

    def named_root(self) -> Any:
        tag = self.u8()
        if tag != 10:
            raise ValueError(f"root tag is {tag}, expected compound")
        self.string()
        return self.payload(tag)

    def payload(self, tag: int) -> Any:
        if tag == 0:
            return None
        if tag == 1:
            return self.i8()
        if tag == 2:
            return self.i16()
        if tag == 3:
            return self.i32()
        if tag == 4:
            return self.i64()
        if tag == 5:
            return self.f32()
        if tag == 6:
            return self.f64()
        if tag == 7:
            length = self.i32()
            return self.read(length)
        if tag == 8:
            return self.string()
        if tag == 9:
            child = self.u8()
            length = self.i32()
            return [self.payload(child) for _ in range(length)]
        if tag == 10:
            value: dict[str, Any] = {}
            while True:
                child = self.u8()
                if child == 0:
                    return value
                name = self.string()
                value[name] = self.payload(child)
        if tag == 11:
            length = self.i32()
            return [self.i32() for _ in range(length)]
        if tag == 12:
            length = self.i32()
            return [self.i64() for _ in range(length)]
        raise ValueError(f"unsupported NBT tag {tag}")


@dataclass
class Chunk:
    path: Path
    x: int
    z: int
    root: dict[str, Any]


def load_chunk_payload(payload: bytes) -> dict[str, Any]:
    if len(payload) < 2:
        raise ValueError("chunk payload is empty")
    length = struct.unpack(">I", payload[:4])[0]
    compression = payload[4]
    body = payload[5 : 4 + length]
    if compression == 1:
        data = gzip.decompress(body)
    elif compression == 2:
        data = zlib.decompress(body)
    elif compression == 3:
        data = body
    else:
        raise ValueError(f"unsupported chunk compression {compression}")
    return NbtReader(data).named_root()


def iter_region_chunks(path: Path) -> list[Chunk]:
    data = path.read_bytes()
    if len(data) < 8192:
        return []
    chunks: list[Chunk] = []
    for index in range(1024):
        offset = int.from_bytes(data[index * 4 : index * 4 + 3], "big")
        sectors = data[index * 4 + 3]
        if not offset or not sectors:
            continue
        start = offset * 4096
        end = start + sectors * 4096
        try:
            root = load_chunk_payload(data[start:end])
        except Exception as exc:
            print(f"warning: skipped {path.name} chunk {index}: {exc}", file=sys.stderr)
            continue
        chunks.append(Chunk(path=path, x=root.get("xPos", 0), z=root.get("zPos", 0), root=root))
    return chunks


def collect_names(value: Any) -> set[str]:
    names: set[str] = set()
    if isinstance(value, dict):
        name = value.get("Name")
        if isinstance(name, str):
            names.add(name)
        for child in value.values():
            names.update(collect_names(child))
    elif isinstance(value, list):
        for child in value:
            names.update(collect_names(child))
    return names


def load_target_blocks() -> list[str]:
    targets: set[str] = set()
    for path in sorted(DATAPACK.glob("*.json")):
        obj = json.loads(path.read_text(encoding="utf-8"))
        targets.update(collect_names(obj))
    return sorted(targets)


def unsigned(value: int) -> int:
    return value & ((1 << 64) - 1)


def decode_palette_counts(data: list[int], palette_size: int, total: int = 4096) -> Counter[int]:
    if palette_size <= 1:
        return Counter({0: total})
    bits = max(4, math.ceil(math.log2(palette_size)))
    mask = (1 << bits) - 1
    expected_compact = math.ceil(total * bits / 64)
    counts: Counter[int] = Counter()

    if len(data) == expected_compact:
        longs = [unsigned(v) for v in data]
        for index in range(total):
            bit_index = index * bits
            long_index = bit_index >> 6
            offset = bit_index & 63
            value = (longs[long_index] >> offset) & mask
            if offset + bits > 64 and long_index + 1 < len(longs):
                value |= (longs[long_index + 1] << (64 - offset)) & mask
            counts[value] += 1
        return counts

    values_per_long = 64 // bits
    for packed in data:
        packed_u = unsigned(packed)
        for slot in range(values_per_long):
            if sum(counts.values()) >= total:
                break
            counts[(packed_u >> (slot * bits)) & mask] += 1
    return counts


def dimension_region_dirs(save: Path) -> list[tuple[str, Path]]:
    candidates = [
        ("overworld", save / "region"),
        ("nether", save / "DIM-1/region"),
        ("end", save / "DIM1/region"),
    ]
    return [(name, path) for name, path in candidates if path.exists()]


def scan(save: Path, targets: set[str]) -> tuple[dict[str, Counter[str]], dict[str, Counter[tuple[str, int]]], Counter[str]]:
    totals: dict[str, Counter[str]] = defaultdict(Counter)
    by_y: dict[str, Counter[tuple[str, int]]] = defaultdict(Counter)
    chunk_counts: Counter[str] = Counter()

    for dimension, region_dir in dimension_region_dirs(save):
        for region in sorted(region_dir.glob("r.*.*.mca")):
            for chunk in iter_region_chunks(region):
                chunk_counts[dimension] += 1
                sections = chunk.root.get("sections", [])
                if not isinstance(sections, list):
                    continue
                for section in sections:
                    if not isinstance(section, dict):
                        continue
                    y_section = section.get("Y")
                    block_states = section.get("block_states")
                    if not isinstance(y_section, int) or not isinstance(block_states, dict):
                        continue
                    palette = block_states.get("palette")
                    if not isinstance(palette, list):
                        continue
                    palette_names = [
                        entry.get("Name") if isinstance(entry, dict) else None
                        for entry in palette
                    ]
                    target_indices = {
                        i: name for i, name in enumerate(palette_names)
                        if isinstance(name, str) and name in targets
                    }
                    if not target_indices:
                        continue
                    data = block_states.get("data")
                    index_counts = decode_palette_counts(data, len(palette)) if isinstance(data, list) else Counter({0: 4096})
                    for index, block in target_indices.items():
                        count = index_counts[index]
                        if not count:
                            continue
                        totals[dimension][block] += count
                        by_y[dimension][(block, y_section * 16)] += count

    return totals, by_y, chunk_counts


def write_reports(save: Path, targets: list[str], totals: dict[str, Counter[str]], by_y: dict[str, Counter[tuple[str, int]]], chunk_counts: Counter[str], report: Path, csv_path: Path) -> None:
    report = report.resolve()
    csv_path = csv_path.resolve()
    report.parent.mkdir(parents=True, exist_ok=True)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        csv_display = csv_path.relative_to(ROOT)
    except ValueError:
        csv_display = csv_path

    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["dimension", "block", "y_section_min", "count"])
        for dimension in sorted(by_y):
            for (block, y), count in sorted(by_y[dimension].items()):
                writer.writerow([dimension, block, y, count])

    lines = [
        "# Worldgen Save Scan",
        "",
        f"- Save: `{save}`",
        f"- Target blocks: {len(targets)}",
        f"- CSV: `{csv_display}`",
        "",
        "## Generated Chunks Scanned",
        "",
    ]
    if chunk_counts:
        for dimension, count in sorted(chunk_counts.items()):
            lines.append(f"- {dimension}: {count}")
    else:
        lines.append("- No terrain chunks found.")
    lines.extend(["", "## Target Block Totals", ""])

    for dimension in sorted(set(chunk_counts) | set(totals)):
        lines.extend([f"### {dimension.title()}", ""])
        if not totals[dimension]:
            lines.append("No target blocks found.")
            lines.append("")
            continue
        lines.append("| Block | Count | Y Sections |")
        lines.append("| --- | ---: | --- |")
        for block, count in totals[dimension].most_common():
            ys = [y for (name, y), _ in by_y[dimension].items() if name == block]
            lines.append(f"| `{block}` | {count} | {min(ys)}..{max(ys)} |")
        lines.append("")

    missing = [block for block in targets if all(totals[d][block] == 0 for d in totals)]
    lines.extend(["## Not Found In Scanned Chunks", ""])
    if missing:
        lines.extend(f"- `{block}`" for block in missing)
    else:
        lines.append("- All target blocks were found.")
    lines.append("")

    report.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("save", type=Path, help="Path to a Minecraft world save directory")
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    args = parser.parse_args()

    save = args.save.resolve()
    if not (save / "level.dat").exists():
        parser.error(f"{save} does not look like a world save; level.dat is missing")

    targets = load_target_blocks()
    totals, by_y, chunk_counts = scan(save, set(targets))
    write_reports(save, targets, totals, by_y, chunk_counts, args.report, args.csv)
    print(f"scanned {sum(chunk_counts.values())} chunks across {len(chunk_counts)} dimensions")
    print(f"wrote {args.report}")
    print(f"wrote {args.csv}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
